### ISSUE TITLE
Possible error in PDBset in libdata.py

### ISSUE THREAD

**Issue by shadow1229** [huhlim/cg2all#1]
__getitem__ part of PDBset calls cg.get_geometry, which input variables are pos (containing coordinates of cg model) and cg.atom_mask_cg, and cg.continuous[0].

However, if cg model have invalid residues ( i.e, if cg.atom_mask_cg[:,0] have some zeros), the shape of pos and cg.atom_mask_cg could be different, due to pos = r_cg[valid_residue, :], while cg.atom_mask_cg does not have equivalent process.

Having invalid residue in the cg model would be inappropriate to run the algorithm, but it would be good to prevent posible error.

**Comment by huhlim** [comment]
Thanks for the issue. As you told me, it is a problem but not likely to happen. I fixed the issue and committed the changes.
