### ISSUE TITLE
magic_number = pickle_module.load(f, **pickle_load_args) EOFError: Ran out of input

### ISSUE THREAD

**Issue by dhq1216dhq** [huhlim/cg2all#13]
Hi,
I'v been trying to use this model, but I came up with bugs showed below:

magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

how can I solve this problem?
thank u so much!

**Comment by huhlim** [comment]
I think the pickled data file has incorrect file size (e.g., incomplete/failed download of the files). Could you check if `PATH_TO_CG2ALL/model/*.ckpt` files have non-zero file sizes?

**Comment by dhq1216dhq** [comment]
thank u so much for replying! I've already solve this problem.It is exactly because when I download the code, I missed the Calpha.ckpt file. So the procedure went wrong.
It is an excellent job, we use this model to transform the 28058 idrs sequences from cg2all. Thank u for your work and hope all the best!










--
发自我的网易邮箱





在 2024-06-23 00:17:45，Lim Heo ***@***.***> 写道：

I think the pickled data file has incorrect file size (e.g., incomplete/failed download of the files). Could you check if PATH_TO_CG2ALL/model/*.ckpt files have non-zero file sizes?
