### ISSUE TITLE
Error when converting a DCD trajectory file

### ISSUE THREAD

**Issue by BFYFlorence** [huhlim/cg2all#3]
I successfully installed the package (CPU version) and tried converting pdb and dcd files from CG to All-atom structures. It worked pretty well for a single pdb file. But I kept getting the following errors when converting a dcd file using the example command line:

Command line: 
convert_cg2all -p tests/1jni.calpha.pdb -d tests/1jni.calpha.dcd -o tests/1jni.calpha.all.dcd --cg CalphaBasedModel

Error:
File "/storage1/fancao/miniconda/envs/cg2all_cpu/lib/python3.8/site-packages/cg2all/lib/libcg.py", line 91, in read_cg
    self.bfactors_cg[:, i_res, i_atm] = self.traj.bfactors[:, atom.index]
AttributeError: 'Trajectory' object has no attribute 'bfactors'

It seemed like mdtraj.Trajectory does not have 'bfactors' but codes are using this as a attribute anyway.

Am I missing something?

**Comment by huhlim** [comment]
Can you check which `mdtraj` version do you use? I modified the original mdtraj library to implement additional features including reading bfactors from PDB files. If the installed version is not "1.9.10.dev0+lim", could you reinstall my custom mdtraj package? (If so, I don't know why the pip installation of cg2all automatically installed the right version of mdtraj...)
```bash
pip install git+http://github.com/huhlim/mdtraj
```

**Comment by BFYFlorence** [comment]
`mdtraj` version is already 1.9.10.dev0+lim and it didn't help if I reinstalled it. 
I just ran `pip install git+http://github.com/huhlim/cg2all` to install `cg2all` (CPU) in a new conda environment. So I am not sure if you could reproduce the same error I encountered.

**Comment by huhlim** [comment]
I figured out the reason for the error. Reading "bfactors" only works for PDB files, so it was trivial to raise the error with DCD file inputs. I fixed the error and committed to the repository. Thank you again for reporting the issue.

**Comment by BFYFlorence** [comment]
Great! Thank you so much.
